[Interface]
PrivateKey = cN7xDmJQB1s/b00GWVOPkl00zsXpAECGp5byFyd2rmA=
Address = 10.200.0.4/32
DNS = 1.1.1.1, 8.8.8.8

[Peer]
PublicKey = ws8CxmiXViWM1MOGJueTGRWULYkuot/E8RnklpLjUm4=
Endpoint = 104.237.250.43:51820
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
