[Interface]
PrivateKey = iF0Yu6FtX+/NRvn7SZ475BpnO/hdKdEVCuwM37fT02A=
Address = 10.200.0.1/24
ListenPort = 51820

[Peer]
# laptop
PublicKey = sOHmvwswW5cbJgXD2ikYbxgNsiFG1tDm04q8LnaGexQ=
AllowedIPs = 10.200.0.2/32
